<#
  check-dist.ps1 — verify dist/tokens.css still matches src/*.json

  WHY THIS EXISTS
  dist/tokens.css is normally generated by `node build.mjs`. This machine has
  no Node runtime, so dist has been hand-maintained - and it drifted. Two real
  defects were found this way:
    1. a whole primary ramp left at the pre-rebrand values
    2. dark badge tints still hard-coding the retired indigo's RGB
  Neither was caught, because nothing compared dist against src.

  This is the guard that would have caught both. It is a subset of what
  `node build.mjs --check` does, covering the parts a hand-edit breaks:
  colour values, and rgb() tints.

  USAGE
    pwsh -File check-dist.ps1        # exit 1 on drift
    pwsh -File check-dist.ps1 -Verbose

  LIMITATION
  It compares VALUES, not structure. It cannot tell you that dist is missing a
  token that src declares, only that the values it does carry disagree. When
  Node is available, prefer `node build.mjs --check`.
#>

[CmdletBinding()]
param([switch]$ShowOk)

$ErrorActionPreference = 'Stop'
$here = Split-Path -Parent $MyInvocation.MyCommand.Path
$src  = Join-Path $here 'src'
$dist = Join-Path $here 'dist\tokens.css'

$css = [System.IO.File]::ReadAllText($dist)

function Flatten($node, [string]$prefix, [hashtable]$out) {
  if ($null -eq $node) { return }
  $v = $node.PSObject.Properties['$value']
  if ($v) { if ($prefix) { $out[$prefix] = $v.Value }; return }
  foreach ($p in $node.PSObject.Properties) {
    if ($p.Name.StartsWith('$')) { continue }
    $key = if ($prefix) { "$prefix.$($p.Name)" } else { $p.Name }
    $val = $p.Value
    if ($val -is [string] -or $val -is [ValueType]) { $out[$key] = $val }
    else { Flatten $val $key $out }
  }
}
# Canonical form for a tint so 0.30 and 0.3 compare equal:
#   rgb(R G B / A)  ->  "r,g,b,a" with A to 3 dp
function NormTint([string]$s) {
  if (-not $s) { return '' }
  $m = [regex]::Match($s,'rgba?\(\s*(\d+)\D+(\d+)\D+(\d+)\D+([\d.]+)\s*\)')
  if (-not $m.Success) { return $s.Trim().ToLower() }
  '{0},{1},{2},{3}' -f $m.Groups[1].Value, $m.Groups[2].Value, $m.Groups[3].Value,
                        ([math]::Round([double]$m.Groups[4].Value, 3))
}

$problems = @()

# ---- 1. colour primitives -------------------------------------------------
$prim = @{}
Flatten (Get-Content (Join-Path $src 'primitive.json') -Raw | ConvertFrom-Json) '' $prim
$checked = 0
foreach ($k in ($prim.Keys | Sort-Object)) {
  if ($k -notlike 'color.*') { continue }
  $want = $prim[$k]
  if ($want -notmatch '^#[0-9a-fA-F]{6}$') { continue }
  $prop = '--ds-' + ($k -replace '\.', '-')
  $m = [regex]::Match($css, [regex]::Escape($prop) + ':\s*(#[0-9a-fA-F]{6})')
  if (-not $m.Success) {
    $problems += "MISSING in dist: $prop (src says $want)"
  } elseif ($m.Groups[1].Value.ToLower() -ne $want.ToLower()) {
    $problems += "DRIFT $prop : dist=$($m.Groups[1].Value)  src=$want"
  }
  $checked++
}

# ---- 2. rgb() tints -------------------------------------------------------
# Tints are written as literals in semantic.json / component.json. They encode a
# specific ramp step's RGB, so they silently go stale when a ramp changes. Every
# tint literal must appear in dist, and dist must not invent one.
$srcRaw = ''
foreach ($f in 'primitive.json','semantic.json','component.json','chart.json') {
  $p = Join-Path $src $f
  if (Test-Path $p) { $srcRaw += "`n" + [System.IO.File]::ReadAllText($p) }
}
$srcTints = [regex]::Matches($srcRaw,'rgb\([^)]*\)') | ForEach-Object { NormTint $_.Value } | Sort-Object -Unique
$distTints = [regex]::Matches($css,'rgb\([^)]*\)')  | ForEach-Object { NormTint $_.Value } | Sort-Object -Unique

foreach ($t in $distTints) {
  if ($srcTints -notcontains $t) { $problems += "STALE tint in dist, not in src: rgb($t)" }
}
foreach ($t in $srcTints) {
  if ($distTints -notcontains $t) { $problems += "MISSING tint in dist: rgb($t)" }
}

# ---- 3. semantic tokens must exist in the RIGHT block --------------------
# The theme is expressed by which block a declaration lives in, not by the
# property name. dist names every token --ds-<path> with no theme prefix, so
# light tokens belong in :root and dark tokens in [data-theme='dark'].
$semDoc = Get-Content (Join-Path $src 'semantic.json') -Raw | ConvertFrom-Json
$lightTokens = @{}; Flatten $semDoc.light '' $lightTokens
$darkTokens  = @{}; Flatten $semDoc.dark  '' $darkTokens

$darkAt = $css.IndexOf("[data-theme='dark']")
if ($darkAt -lt 0) { $problems += "dist has no [data-theme='dark'] block at all" }
$rootCss = if ($darkAt -lt 0) { $css } else { $css.Substring(0,$darkAt) }
$darkCss = if ($darkAt -lt 0) { '' } else { $css.Substring($darkAt) }

foreach ($k in ($lightTokens.Keys | Sort-Object)) {
  $prop = '--ds-' + ($k -replace '\.', '-')
  if (-not $rootCss.Contains($prop + ':')) { $problems += "MISSING light token in :root -> $prop" }
}
foreach ($k in ($darkTokens.Keys | Sort-Object)) {
  $prop = '--ds-' + ($k -replace '\.', '-')
  if (-not $darkCss.Contains($prop + ':')) { $problems += "MISSING dark token in [data-theme='dark'] -> $prop" }
}
$semChecked = $lightTokens.Count + $darkTokens.Count

# ---- 4. a dark override must actually differ from the light value --------
# A dark declaration identical to its light counterpart is dead weight: it
# looks meaningful, survives a light-theme rebrand by accident, and hides the
# fact that the token is not theme-dependent. Flag it so the redundancy is a
# decision rather than an accident.
function Decl([string]$block, [string]$prop) {
  $m = [regex]::Match($block, [regex]::Escape($prop) + ':\s*([^;]+);')
  if ($m.Success) { return $m.Groups[1].Value.Trim() }
  return $null
}
# Tokens that are theme-independent BY DESIGN. Re-declaring them in the dark
# block is redundant, and redundancy here is actively dangerous: it looks
# meaningful, so a later rebrand of the light value silently leaves the dark
# theme behind. These are allow-listed deliberately - if you add one, say why.
$ThemeIndependent = @(
  # a solid fill carries a light label in BOTH themes; this is what makes
  # .solid usable without per-theme label tokens. See check-contrast.ps1.
  'content.on-solid',
  # density is a user preference, not a theme concern
  'density.cell-pad-compact', 'density.cell-pad-comfortable',
  'density.row-compact',     'density.row-comfortable',
  'density.section-compact', 'density.section-comfortable',
  # currently theme-invariant; re-point when the ramps diverge
  'border.inverse', 'border.strong'
)

$redundant = 0
foreach ($k in ($lightTokens.Keys | Sort-Object)) {
  $prop = '--ds-' + ($k -replace '\.', '-')
  $lv = Decl $rootCss $prop
  $dv = Decl $darkCss  $prop
  if ($null -ne $dv -and $null -ne $lv -and $dv -eq $lv) {
    if ($ThemeIndependent -contains $k) { continue }
    $problems += "REDUNDANT dark override, value identical to light -> $prop : $lv"
    $redundant++
  }
}

# ---- 5. a dark override must differ from what src says ------------------
# The dark block's whole job is to replace the light value. If src declares a
# distinct dark value but dist copied the light one, the theme is silently broken.
foreach ($k in ($darkTokens.Keys | Sort-Object)) {
  $prop = '--ds-' + ($k -replace '\.', '-')
  $want = $darkTokens[$k]
  # src dark value is an alias like {color.neutral.800}; resolve to the var form dist uses
  $wantVar = $null
  if ($want -match '^\{([^}]+)\}$') { $wantVar = 'var(--ds-' + ($matches[1] -replace '\.', '-') + ')' }
  $got = Decl $darkCss $prop
  if ($null -eq $got) { continue }   # already reported as missing
  if ($null -ne $wantVar -and $got -ne $wantVar) {
    $problems += "DARK VALUE DRIFT $prop : dist=$got  src wants $wantVar"
  }
}

# ---- report ---------------------------------------------------------------
"checked $checked colour primitives, $semChecked semantic tokens ($($lightTokens.Count) light / $($darkTokens.Count) dark), $($srcTints.Count) tints"
if ($problems.Count -eq 0) {
  "dist/tokens.css is in sync with src/*.json"
  exit 0
}
""
"$($problems.Count) problem(s):"
$problems | ForEach-Object { "  $_" }
exit 1
