<#
  build-preview.ps1 - generate the self-contained brand preview.

  WHY THIS EXISTS
  jovalen-brand-preview.html has to work as a single file, because .html is
  associated with a retired Internet Explorer on this machine and will not
  open. That means it cannot <link> the stylesheet or <img> the SVGs.

  Those constraints are exactly what let it rot. It was hand-assembled once and
  then never rebuilt, so it silently kept:
    - the pre-rebrand palette, and
    - lockups on the OLD viewBoxes (96x24 / 72x62), i.e. built before the
      textLength 68 -> 92 fix, so the wordmark was still visibly collapsed.
  Nothing detected either, because nothing compared it to the sources.

  So it is generated now, from brand/preview.html, every time. Edit
  brand/preview.html and re-run this; never edit the output.

  USAGE
    pwsh -File build-preview.ps1           # write ../jovalen-brand-preview.html
    pwsh -File build-preview.ps1 -Check    # fail if the output is stale

  WHAT IT INLINES
    ../funnel-os/packages/tokens/dist/tokens.css  -> a <style> block
    every relative .svg referenced by the source   -> a base64 data URI
#>

[CmdletBinding()]
param([switch]$Check)

$ErrorActionPreference = 'Stop'
$here  = Split-Path -Parent $MyInvocation.MyCommand.Path
$root  = Split-Path -Parent $here
$src   = Join-Path $here 'preview.html'
$out   = Join-Path $root 'jovalen-brand-preview.html'
$css   = Join-Path $root 'funnel-os\packages\tokens\dist\tokens.css'

function B64([string]$path) {
  [Convert]::ToBase64String([System.IO.File]::ReadAllBytes($path))
}

$html = [System.IO.File]::ReadAllText($src)

# ---- 1. inline the token stylesheet ---------------------------------------
# The source links it relatively; swap the <link> for the file's contents so
# the output has no external dependency.
$cssText = [System.IO.File]::ReadAllText($css)
$linkRe  = '<link rel="stylesheet" href="\.\./funnel-os/packages/tokens/dist/tokens\.css"\s*/>'
if ($html -notmatch $linkRe) { throw "could not find the tokens.css <link> in preview.html - has its path changed?" }
# LF, never CRLF. The output is committed and .gitattributes normalises every
# text file to LF, so a generator emitting CRLF produces a file that can never
# match its own output on a fresh clone: git stores LF, the checkout is LF, and
# the build here produces CRLF. -Check then reports the committed artefact as
# stale in a clean checkout while passing in the working tree that made it.
# Two hardcoded "`r`n" caused exactly that.
$styleBlock = "<style>`n    /* ---- inlined from funnel-os/packages/tokens/dist/tokens.css ---- */`n" +
              ($cssText -replace '(?m)^', '    ') + "  </style>"
$html = [regex]::Replace($html, $linkRe, [System.Text.RegularExpressions.MatchEvaluator]{ param($m) $styleBlock })

# ---- 2. inline every relative svg ----------------------------------------
# Paths are relative to brand/, so resolve against $here. Anything not found is
# a hard error: a silently-missing logo in a brand document is the worst
# possible failure mode.
#
# Only src= is rewritten, deliberately. preview.html also shows the reader a
# copy-pasteable <link rel="icon" href="brand/favicon/favicon.svg"> snippet as
# escaped documentation text. That is an instruction to the reader, not an
# asset this page loads - rewriting it to a data URI would corrupt the snippet
# and stop it being usable. Every real asset in the page is an <img src>.
$inlined = @{}
$missing = @()
$svgRe = 'src="((?!https?:|data:|#)([^"]+\.svg))"'
$html = [regex]::Replace($html, $svgRe, {
  param($m)
  $ref = $m.Groups[1].Value
  $full = Join-Path $here ($ref -replace '/', '\')
  if (-not (Test-Path $full)) { $script:missing += $ref; return $m.Value }
  if (-not $inlined.ContainsKey($full)) { $inlined[$full] = B64 $full }
  'src="data:image/svg+xml;base64,' + $inlined[$full] + '"'
})

if ($missing.Count) { throw "referenced but not found: $($missing -join ', ')" }

# The page's own <head> favicon is a real dependency and must be inlined too,
# or the file only works from the folder it was built in. The lookbehind skips
# the escaped copy-pasteable snippet (&lt;link ...&gt;), which is documentation.
$inlinedHead = [ordered]@{}
$headRe = '(?<!&lt;)<link(?<pre>[^>]*?)href="(?<ref>(?!https?:|data:|#)([^"]+\.svg))"'
$html = [regex]::Replace($html, $headRe, {
  param($m)
  $ref = $m.Groups['ref'].Value
  $full = Join-Path $here ($ref -replace '/', '\')
  if (-not (Test-Path $full)) { $script:missing += $ref; return $m.Value }
  if (-not $inlinedHead.Contains($full)) { $inlinedHead[$full] = B64 $full }
  '<link' + $m.Groups['pre'].Value + 'href="data:image/svg+xml;base64,' + $inlinedHead[$full] + '"'
})
if ($missing.Count) { throw "referenced but not found: $($missing -join ', ')" }

# ---- 3. write or verify ---------------------------------------------------
$stamp = "<!-- GENERATED by brand/build-preview.ps1 from brand/preview.html - do not edit -->"
if (-not $html.StartsWith('<!--')) { $html = $stamp + "`n" + $html }

if ($Check) {
  if (-not (Test-Path $out)) { "STALE: $out does not exist"; exit 1 }
  $cur = [System.IO.File]::ReadAllText($out)
  if ($cur -ne $html) { "STALE: $out is out of date - re-run without -Check"; exit 1 }
  "$([System.IO.Path]::GetFileName($out)) is up to date ($(($inlined.Count + $inlinedHead.Count)) SVGs, $([math]::Round($html.Length/1024)) KB)"
  exit 0
}

[System.IO.File]::WriteAllText($out, $html, (New-Object System.Text.UTF8Encoding($false)))
$all = @($inlined.Keys) + @($inlinedHead.Keys) | Sort-Object -Unique
"$([System.IO.Path]::GetFileName($out)) written: $([math]::Round($html.Length/1024)) KB"
"  inlined $($all.Count) distinct SVGs:"
$all | ForEach-Object { "    " + $_.Replace($here + '\','') }
"  inlined tokens.css ($([math]::Round($cssText.Length/1024)) KB)"
$leftover = [regex]::Matches($html,'(?:src|href)="(?!https?:|data:|#)([^"]*)"')
"  remaining relative refs: $($leftover.Count) (expect 1: the escaped copy-paste snippet)"
$leftover | ForEach-Object { "    " + $_.Value }
exit 0
