/**
 * Insights and Recommendations — §60's four claim types, §58's evidence, §63's
 * unconfirmed marking, §64's ten fields.
 *
 * Two rules do most of the work here, and both are enforced by the API rather
 * than by this page:
 *
 *   1. **§63** — content generated by the system that a human has not confirmed
 *      must be visibly marked. A recommendation that reads exactly like a
 *      measured fact is the failure this exists to prevent, so `confirmed` is
 *      rendered before the title, not as a badge in the corner.
 *
 *   2. **§64** — all ten fields are present, always. The card does not collapse
 *      "effort" or "impact" when they are unmeasured; an absent field is shown
 *      as `unknown`, because omitting it is indistinguishable from omitting it
 *      by mistake.
 */

import * as React from 'react';
import { Badge, Button, StatusPill } from '@funnelos/ui';
import { font, space } from '@funnelos/ui';
import { api, useMutation, useQuery, type RankedRecommendation } from '@funnelos/api-client';
import type { ClaimType, Evidence } from '@funnelos/contracts';
import { PageHeader } from '../shell/AppShell.js';
import { AsyncBoundary, Panel } from '../composites/AsyncBoundary.js';

/* ------------------------------------------------------------------ *
 * §60: the four claim types
 *
 * The distinction is the whole point of the feature, so it is carried by a word
 * as well as a colour. A colour-only distinction here means a screen-reader user
 * is told "analysis" and a sighted user is told "analysis" by a hue, and one of
 * those two is guessing.
 * ------------------------------------------------------------------ */

const CLAIM_TONE: Record<ClaimType, 'neutral' | 'brand' | 'info' | 'warning'> = {
  fact: 'neutral',
  analysis: 'brand',
  hypothesis: 'warning',
  recommendation: 'info',
};

const CLAIM_MEANING: Record<ClaimType, string> = {
  fact: 'Measured. Taken directly from a connected source.',
  analysis: 'Interpreted. Derived from facts by a stated method.',
  hypothesis: 'Guessed. Plausible and unproven; treat as a question.',
  recommendation: 'Proposed. A suggested course of action, not a finding.',
};

/**
 * §52 gives Insights and Recommendations separate nav items, so they are
 * separate screens. They share the filter and the claim-type vocabulary because
 * they are the same kind of object — the plan's §60 treats a recommendation as
 * a claim type, not as a different kind of thing.
 */
export function InsightsPage() {
  const [includeDismissed, setIncludeDismissed] = useDismissedToggle();
  const insights = useQuery((signal) => api.insights.list(includeDismissed, signal), [includeDismissed]);

  return (
    <div className="os-page">
      <PageHeader
        title="Insights"
        subtitle="What the data is saying. Every claim is labelled with what kind of claim it is, because a measurement and a guess look identical until you are told which one you are reading."
      />

      <DismissedFilter includeDismissed={includeDismissed} setIncludeDismissed={setIncludeDismissed} subject="insight" />

      <Panel title="Insights">
        <AsyncBoundary
          query={insights}
          loadingLabel="Loading insights"
          emptyTitle={includeDismissed ? 'No insights at all' : 'No insights'}
          emptyBody={
            includeDismissed
              ? 'This workspace has produced no insights, dismissed or otherwise.'
              : 'Every insight has been dismissed. Turn on "Show dismissed" to see them and undo any of them.'
          }
        >
          {(rows) => (
            <div className="os-grid os-grid--cards">
              {rows.map((i) => (
                <InsightCard key={i.id} insight={i} />
              ))}
            </div>
          )}
        </AsyncBoundary>
      </Panel>
    </div>
  );
}

export function RecommendationsPage() {
  const [includeDismissed, setIncludeDismissed] = useDismissedToggle();
  const recs = useQuery((signal) => api.recommendations.list(includeDismissed, signal), [includeDismissed]);

  return (
    <div className="os-page">
      <PageHeader
        title="Recommendations"
        subtitle="What the system suggests doing, and why. Anything not yet checked by a person is marked as unconfirmed before you read the title, because an unverified suggestion that reads like a measured fact is the failure §63 exists to prevent."
      />

      <DismissedFilter includeDismissed={includeDismissed} setIncludeDismissed={setIncludeDismissed} subject="recommendation" />

      <Panel title="Recommendations">
        <AsyncBoundary
          query={recs}
          loadingLabel="Loading recommendations"
          emptyTitle={includeDismissed ? 'No recommendations at all' : 'No recommendations'}
          emptyBody="Nothing is being suggested. Recommendations are produced from gaps in the funnel, so a funnel with no measurable gaps produces none."
        >
          {(rows) => (
            <div className="os-col" style={{ gap: space['4'] }}>
              <BandLegend />
              {rows.map((r) => (
                <RecommendationCard key={r.id} rec={r} />
              ))}
            </div>
          )}
        </AsyncBoundary>
      </Panel>
    </div>
  );
}

const useDismissedToggle = () => React.useState(false);

function DismissedFilter({
  includeDismissed,
  setIncludeDismissed,
  subject,
}: {
  includeDismissed: boolean;
  setIncludeDismissed: (v: boolean) => void;
  /** Singular, for the sentence below the control. */
  subject: 'insight' | 'recommendation';
}) {
  const id = `show-dismissed-${subject}s`;
  return (
    <Panel title="Filter">
      <div className="os-col" style={{ gap: space['2'] }}>
        <label className="os-row" htmlFor={id} style={{ gap: space['2'] }}>
          <input
            id={id}
            type="checkbox"
            checked={includeDismissed}
            onChange={(e) => setIncludeDismissed(e.target.checked)}
            style={{ inlineSize: space['3'], blockSize: space['3'] }}
          />
          <span className="os-tiny">Show dismissed</span>
        </label>
        <p className="os-tiny">
          {includeDismissed
            ? `Dismissed ${subject}s are included. Dismissing hides something rather than deleting it, and the API keeps serving it on request.`
            : `Dismissed ${subject}s are hidden. Nothing has been removed — dismiss and restore both write an audit entry.`}
        </p>
      </div>
    </Panel>
  );
}

/* ------------------------------------------------------------------ *
 * Insight
 * ------------------------------------------------------------------ */

function InsightCard({ insight }: { insight: import('@funnelos/contracts').Insight }) {
  const dismiss = useMutation(() => api.insights.dismiss(insight.id), [insight.id]);
  const restore = useMutation(() => api.insights.restore(insight.id), [insight.id]);
  const busy = dismiss.pending || restore.pending;
  const failed = dismiss.error ?? restore.error;

  return (
    <article className="os-card os-card--flush" style={{ opacity: insight.dismissed ? 0.6 : 1 }}>
      <div className="os-card__header">
        {/*
          The claim type is first, and it is a word. Everything else on this
          card is downstream of it: a "fact" is something that happened, a
          "hypothesis" is something the system is guessing at.
        */}
        <Badge tone={CLAIM_TONE[insight.claimType]}>{insight.claimType}</Badge>
        <StatusPill
          tone={insight.severity === 'critical' ? 'danger' : insight.severity === 'warning' ? 'warning' : 'neutral'}
        >
          {insight.severity}
        </StatusPill>
      </div>

      <p className="os-card__body" style={{ fontWeight: font.weight.medium }}>
        {insight.claim}
      </p>

      <p className="os-tiny">{CLAIM_MEANING[insight.claimType]}</p>

      <EvidenceList evidence={insight.evidence} />

      <div className="os-row" style={{ justifyContent: 'space-between' }}>
        <span className="os-tiny os-num" title="§58 confidence">
          confidence {(insight.confidence * 100).toFixed(0)}%
        </span>
        {insight.dismissed ? (
          <Button size="sm" variant="ghost" disabled={busy} onClick={() => restore.run()}>
            Restore
          </Button>
        ) : (
          <Button size="sm" variant="ghost" disabled={busy} onClick={() => dismiss.run()}>
            Dismiss
          </Button>
        )}
      </div>

      {failed ? (
        <p className="os-tiny" role="alert">
          {failed.message}
        </p>
      ) : null}
    </article>
  );
}

/* ------------------------------------------------------------------ *
 * Recommendation — §64's ten fields
 * ------------------------------------------------------------------ */

function RecommendationCard({ rec }: { rec: RankedRecommendation }) {
  const accept = useMutation(() => api.recommendations.accept(rec.id), [rec.id]);
  const dismiss = useMutation(() => api.recommendations.dismiss(rec.id), [rec.id]);
  const confirm = useMutation(() => api.recommendations.confirm(rec.id), [rec.id]);
  const busy = accept.pending || dismiss.pending || confirm.pending;
  const failed = accept.error ?? dismiss.error ?? confirm.error;

  return (
    <article
      className="os-card os-card--flush"
      style={{
        opacity: rec.status === 'dismissed' ? 0.6 : 1,
        // §63: unconfirmed system-generated content is marked, and the mark is
        // a border as well as a badge so it survives greyscale and forced
        // colours, where a badge tint is simply the background colour again.
        borderInlineStart: rec.confirmed ? undefined : `var(--ds-border-width-thick) solid ${'var(--ds-status-warning-border)'}`,
      }}
    >
      <div className="os-card__header">
        {/*
          §63. Placed before the title, not after it. An unconfirmed
          recommendation has to be marked before a reader has decided to act on
          it, and a marker in the corner of a card is read after the title.
        */}
        {rec.confirmed ? (
          <Badge tone="success" dotLabel="Confirmed by a person">
            confirmed
          </Badge>
        ) : (
          <Badge tone="warning" dotLabel="Not yet confirmed by a person">
            unconfirmed
          </Badge>
        )}

        <StatusPill
          tone={
            rec.priorityBand === 'do-now' ? 'danger' : rec.priorityBand === 'plan' ? 'info' : 'neutral'
          }
        >
          {rec.priorityBand}
        </StatusPill>

        <StatusPill tone={rec.status === 'accepted' ? 'success' : rec.status === 'dismissed' ? 'neutral' : 'info'}>
          {rec.status}
        </StatusPill>
      </div>

      <h3 className="os-card__title" style={{ fontSize: font.size.base }}>
        {rec.title}
      </h3>
      <p className="os-card__body">{rec.rationale}</p>

      {/*
        The four §64 scalars, always present. `impact` and `effort` are the two
        a system is most tempted to hide when it is unsure, and hiding them is
        how an unranked suggestion ends up looking ranked.
      */}
      <dl className="os-defs">
        <dt>Impact</dt>
        <dd>{rec.impact}</dd>
        <dt>Effort</dt>
        <dd>{rec.effort}</dd>
        <dt>Confidence</dt>
        <dd className="os-num">{(rec.confidence * 100).toFixed(0)}%</dd>
        <dt>Priority score</dt>
        <dd className="os-num">{rec.priority.toFixed(1)}</dd>
      </dl>

      <EvidenceList evidence={rec.evidence} />

      <div className="os-row" style={{ flexWrap: 'wrap' }}>
        {/*
          §63's rule again, at the point of action: accepting is blocked until
          a person has confirmed. The API refuses an unconfirmed accept with a
          400, and this button is disabled for the same reason — but the reason
          is on the button, because a disabled control with no explanation is
          the single most common way an app tells a user nothing.
        */}
        <Button
          variant="solid"
          size="sm"
          disabled={busy || !rec.confirmed || rec.status === 'accepted'}
          title={rec.confirmed ? undefined : 'Confirm this recommendation before accepting it (§63)'}
          onClick={() => accept.run()}
        >
          Accept
        </Button>
        <Button
          variant="secondary"
          size="sm"
          disabled={busy || rec.confirmed}
          title={rec.confirmed ? 'Already confirmed' : 'Mark this as checked by a person (§63)'}
          onClick={() => confirm.run()}
        >
          Confirm
        </Button>
        <Button variant="ghost" size="sm" disabled={busy} onClick={() => dismiss.run()}>
          Dismiss
        </Button>
      </div>

      {failed ? (
        <p className="os-tiny" role="alert">
          {failed.message}
        </p>
      ) : null}
    </article>
  );
}

/**
 * §58: evidence, or the claim does not render.
 *
 * A claim with no evidence is rendered as an explicit refusal rather than as a
 * bare sentence. The API is supposed to prevent these; this is the client-side
 * half of that rule, and the reason it exists is that a fixture generator can
 * produce anything.
 */
function EvidenceList({ evidence }: { evidence: Evidence[] }) {
  if (evidence.length === 0) {
    return (
      <p className="os-tiny" role="note" style={{ color: 'var(--ds-status-danger-fg)' }}>
        No evidence attached. §58 requires it, so this claim should not be shown at all.
      </p>
    );
  }
  return (
    <div className="os-evidence">
      <span className="os-evidence__label">Evidence (§58)</span>
      {evidence.map((ev) => (
        <div key={ev.id} className="os-evidence__row">
          {/*
            The metric name, then the value, then the window it was measured
            over. All three, because "38%" with no window is not evidence — it
            is a number, and a number without a window cannot be checked.
          */}
          <span className="os-evidence__value">{ev.metricName}</span>
          <span className="os-num">{ev.value}</span>
          <span className="os-tiny os-muted">
            {ev.comparisonWindow} · {ev.source}
          </span>
        </div>
      ))}
    </div>
  );
}

function BandLegend() {
  return (
    <p className="os-tiny">
      <strong>do-now</strong> is high impact and low effort. <strong>plan</strong> is worth scheduling.{' '}
      <strong>skip</strong> is suggested and not worth doing now — it is shown rather than hidden, because
      &ldquo;why was this not recommended?&rdquo; is a question people ask and a silent filter cannot answer.
    </p>
  );
}
